### ISSUE TITLE
Calls to `document` kill my isomorphic app.

### ISSUE THREAD

**Issue by SudoPlz** [jquense/react-bootstrap-modal#8]
Ok, I know this is probably not your problem but would you be kind enough to help me with it?

I get this error:
```javascript
/Users/Dynopia/Development/DS_Stalker_Frontend/node_modules/react-bootstrap-modal/lib/Modal.js:26
  var modal = document.createElement("div"),
              ^
ReferenceError: document is not defined
    at /Users/Dynopia/Development/DS_Stalker_Frontend/node_modules/react-bootstrap-modal/lib/Modal.js:26:15
    at Object.<anonymous> (/Users/Dynopia/Development/DS_Stalker_Frontend/node_modules/react-bootstrap-modal/lib/Modal.js:46:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Dynopia/Development/DS_Stalker_Frontend/bin/serverEntryPoint.js:1752:19)
    at __webpack_require__ (/Users/Dynopia/Development/DS_Stalker_Frontend/bin/serverEntryPoint.js:20:30)
```

I'm building an isomorphic app so calls to `document` in your Modal.js are TOTALLY accepted when they run browser side but NOT when they run on the server side through node. 
What can I do to stop getting this error, its killing me..!

ps: I use 1 webpack config file for the server and 1 for client side.

**Comment by SudoPlz** [comment]
For now I moved the 2 basic functions that use DOM elements (`getZIndex` and `getStyles`) inside `Modal.prototype.componentDidMount`.

Any DOM element calls inside `componentDidMount` are assumed to be browser only code, and thus cause no problems to webpack.

If this is no fuss for you would you be kind enough to also do this in your repo?
